### ISSUE TITLE
Please add the opam package to https://github.com/coq/opam-coq-archive

### ISSUE THREAD

**Issue by gares** [math-comp/fourcolor#10]
In this way benchmarks like this one (for https://github.com/coq/coq/pull/9905)
  https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/667/console
can run on fourcolor too.

**Comment by gares** [comment]
I can take care of this issue, and make an opam package with version `.dev` (a package that points to the head of the master branch).

But while I'm at it I'd like to know if a release is foreseen. A `.dev` package are moving target and can only live in the development repository. The main repository (called released), the one Coq's final users pull from, only accepts package with a fixed version (eg a git tag that points to a precise commit).
If a release is made I'll package that too.

**Comment by proux01** [comment]
Ping?

**Comment by gares** [comment]
See https://github.com/coq/opam-coq-archive/pull/628 for the dev package

@ggonthier if you tag the current master (eg `v1.0`) then I can package it also for the `released` repository (the one for users, not for developers/CI)

**Comment by ggonthier** [comment]
Sure, but in #12 you seem to indicate we should be at 2.0??

**Comment by gares** [comment]
Sorry we are not talking about the same version.

The version up there in the opam file is the "opam file format" one.

Here I'm talking about a version of the formalization of the four color theorem (like version 1.8.0 of math-comp). What the packages in the `released` archive point to is a precise archive (corresponding to a version of the software). See https://github.com/math-comp/fourcolor/releases 

The "dev" package I'm adding to the `extra-dev` repository points to the master branch, that is a moving target (appropriate for CI, but not for final users). It will let @proux01 benchmark his improvements to vmcompute on the 4ct via our "pendulum" https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/

**Comment by gares** [comment]
I'm closing this since the dev package is there. @ggonthier ping me when/if you make a release and I'll add the package to the released archive too.

**Comment by ggonthier** [comment]
Ping @gares for a v1.2 release (see notes explaining the number).

**Comment by gares** [comment]
Very good! https://github.com/coq/opam-coq-archive/pull/630
