### ISSUE TITLE
OPAM package for mathcomp-1.14.0

### ISSUE THREAD

**Issue by chdoc** [math-comp/fourcolor#35]
It would be nice to have OPAM packages of `coq-fourcolor` for MathComp 1.14.0 (and maybe also 1.13.0), so that I can make another release of the graph theory library.

**Comment by palmskog** [comment]
I think this can be closed now, since [1.2.4](https://github.com/coq-community/fourcolor/releases/tag/v1.2.4) with support for 1.14.0 has been out for a while.
