### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by ASamSam** [math-comp/fourcolor#63]
Hello. 
trying to install, and have this problem.
not sure If it really comes from mathcomp ... can you help me please?
![image](https://github.com/user-attachments/assets/79181912-5aa5-4cf7-9616-dabd68e0880b)

**Comment by ybertot** [comment]
This image does not indicate what commands you ran to install the development.

As a newcomer, you should not aim for a dev version of the development.  You should instead install a well-established version.  Here is a sequence of commands that installs the development in a dedicated opam switch:

```
opam switch create fct ocaml.4.14.3
opam repo add coq-released https://coq.inria.fr/opam/released
opam install coq-fourcolor
```

If you do not want to use a dedicated opam switch, do not include the first line above.  This is is already what is explained in the README.md file of the project.

If your last use of opam was long ago, it may be useful to add the following command before the `opam install coq-fourcolor` command:

```
opam update
```

**Comment by ASamSam** [comment]
yes, thank you. somehow, I don`t know why the dev version was pointed, but I did already resolve the issue with a similar approach.
